name: Unit Test Action
description: Action to run unit tests
inputs:
  python_version:
    description: "Python version you want to use"
    default: '3.10'
  requirements_path:
    description: "Path to requirements.txt"
    required: true
    
runs:
  using: "composite"
  steps:
    - name: Checkout repo
      uses: actions/checkout@master

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{inputs.python_version}}

    steps:
      - name: Install dependencies
        shell: bash
        run: |
          pip install -r ${{inputs.requirements_path}}

    steps:
      - name: Install dependencies
        shell: bash
        run: |
          pytest ${{inputs.unit_test_path}}

