name: Greeting data academy

on:
  push:
    branches-ignore: [main]

env:
  DAY_OF_WEEK: monday
  MY_USERNAME: ${{ github.actor }}

jobs:
  greeting_job:
    runs-on: self-hosted
    env:
      GREETING: Hello
    steps:
      - name: "Say 'Hello Data Academy 7th edition, this is $DAY_OF_WEEK's first exercise! I'm $MY_USERNAME!'"
        run: echo "$GREETING $ACADEMY_TYPE Academy 7th edition, this is $DAY_OF_WEEK's first exercise! I'm $MY_USERNAME!"
        env:
          ACADEMY_TYPE: Data

